### PR TITLE
fix: don't proceed with ConfigureShorebird if init fails

### LINKED ISSUE #211: fix: patches sometimes uninstall right after install (package:flutter_foreground_task)
Two customers have reported a bad (occasional) interaction between Shorebird and some plugins which create a FlutterEngine, (but don't actually use it), causing Shorebird's launch tracking to get confused and think a patch crashed an uninstall it right away.

This only happens if the plugin (in this case, package:flutter_foreground_task) is invoked right between when a patch is installed before it it successfully launched from.

The bug is our fault.  Our launch tracking gets confused by (surprising) behavior from the plugin which we need to fix.

@bryanoltman is working on a fix, which we hope to release later this week.  Thanks!

### PR DESCRIPTION
**Pull request by bryanoltman**
If `shorebird_init` fails, don't proceed to report a launch start or start an update thread.

Fixes https://github.com/shorebirdtech/updater/issues/211

### CODE REVIEW

File: shell/common/shorebird/shorebird.cc [hunk 1]
```diff
@@ -125,8 +125,11 @@ void ConfigureShorebird(std::string code_cache_path,
     app_parameters.original_libapp_paths_size = c_paths.size();
 
     // shorebird_init copies from app_parameters and shorebirdYaml.
-    shorebird_init(&app_parameters, ShorebirdFileCallbacks(),
-                   shorebird_yaml.c_str());
+    auto init_result = shorebird_init(&app_parameters, ShorebirdFileCallbacks(),
```
Comment (felangel) [inline shell/common/shorebird/shorebird.cc]: Is there any way to unit test this to ensure we don't have a regression?

**Review by eseidel — CHANGES_REQUESTED** [review]
Won't this mean that only the first thread to call shorebird will have its snapshot replaced and all others will use the release snapshot?

**Comment by eseidel** [comment]
I believe Firebase Cloud Messaging is an example of where a FlutterEngine is created (and executed) before the main thread is.  I think this change as written would cause FCM to use the patch, but then the main app to use the release version?

**Comment by bryanoltman** [comment]
Ah, I had been testing with workmanager, which will be started by the app, but you're absolutely right (just confirmed in my FCM app test). I've updated to move the return further down, which will ensure the snapshot is properly set for the app in the FCM case.

File: shell/common/shorebird/shorebird.cc [hunk 2]
```diff
@@ -156,16 +157,19 @@ void ConfigureShorebird(std::string code_cache_path,
...
-    // Once start_update_thread is called, the next_boot_patch* functions may
-    // change their return values if the shorebird_report_launch_failed
-    // function is called.
-    shorebird_report_launch_start();
-
   } else {
     FML_LOG(INFO) << "Shorebird updater: no active patch.";
   }
 
+  if (!init_result) {
```
Comment (eseidel) [inline shell/common/shorebird/shorebird.cc:173]:
```suggestion
  // We are careful only to report a launch start in the case where it's the first time we've
  // configured shorebird this process.  Otherwise we could end up in a case where
  // we report a launch start, but never a completion (e.g. from package:flutter_work_manager
  // which sometimes creates a FlutterEngine (and thus configures shorebird) but never
  // runs it.  The proper fix for this is probably to move the launch_start() call to be later
  // in the lifecycle (when the snapshot is loaded and run, rather than when FlutterEngine
  // is initialized).  This "hack" will still have a problem where FlutterEngine is initialized
  // but never run before the app is quit, could still cause us to suddenly mark-bad a patch
  // that was never actually attempted to launch.
  if (!init_result) {
```

**Review by eseidel — APPROVED** [review]
This is the most surgical fix, and will *probably* work, but I think is probably not the right fix for this code long term.  I left a long TODO to try and cover that.
